# Generated by Django 5.2.13 on 2026-04-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('harga_paket', models.DecimalField(decimal_places=2, max_digits=15)),
                ('jumlah_award_miles', models.IntegerField()),
            ],
            options={
                'db_table': 'award_miles_package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_member', models.CharField(max_length=100)),
                ('kode_hadiah', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'redeem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('kode_hadiah', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True)),
                ('valid_start_date', models.DateField()),
                ('program_end', models.DateField()),
            ],
            options={
                'db_table': 'hadiah',
                'managed': False,
            },
        ),
    ]
