# Generated by Django 5.2.13 on 2026-04-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardMilesPackage',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('harga_paket', models.DecimalField(decimal_places=2, max_digits=15)),
                ('jumlah_award_miles', models.IntegerField()),
            ],
            options={
                'db_table': 'award_miles_package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bandara',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('negara', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bandara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimMissingMiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_member', models.CharField(max_length=100)),
                ('email_staf', models.CharField(blank=True, max_length=100, null=True)),
                ('maskapai', models.CharField(max_length=10)),
                ('bandara_asal', models.CharField(max_length=3)),
                ('bandara_tujuan', models.CharField(max_length=3)),
                ('tanggal_penerbangan', models.DateField()),
                ('flight_number', models.CharField(max_length=10)),
                ('nomor_tiket', models.CharField(max_length=20)),
                ('kelas_kabin', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], max_length=20)),
                ('pnr', models.CharField(max_length=10)),
                ('status_penerimaan', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'claim_missing_miles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hadiah',
            fields=[
                ('kode_hadiah', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True)),
                ('valid_start_date', models.DateField()),
                ('program_end', models.DateField()),
                ('id_penyedia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hadiah',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('nomor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email_member', models.CharField(max_length=100)),
                ('tanggal_habis', models.DateField()),
                ('tanggal_terbit', models.DateField()),
                ('negara_penerbit', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('Paspor', 'Paspor'), ('KTP', 'KTP'), ('SIM', 'SIM')], max_length=30)),
            ],
            options={
                'db_table': 'identitas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maskapai',
            fields=[
                ('kode_maskapai', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_maskapai', models.CharField(max_length=100)),
                ('id_penyedia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'maskapai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nomor_member', models.CharField(max_length=20, unique=True)),
                ('tanggal_bergabung', models.DateField()),
                ('id_tier', models.CharField(max_length=10)),
                ('award_miles', models.IntegerField(default=0)),
                ('total_miles', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('email_mitra', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_penyedia', models.IntegerField()),
                ('nama_mitra', models.CharField(max_length=100)),
                ('tanggal_kerja_sama', models.DateField()),
            ],
            options={
                'db_table': 'mitra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('salutation', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.')], max_length=10)),
                ('first_mid_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=5)),
                ('mobile_number', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('kewarganegaraan', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pengguna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Penyedia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'penyedia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_member', models.CharField(max_length=100)),
                ('kode_hadiah', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'redeem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_staf', models.CharField(blank=True, max_length=20, null=True)),
                ('kode_maskapai', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'staf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id_tier', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('minimal_frekuensi_terbang', models.IntegerField()),
                ('minimal_tier_miles', models.IntegerField()),
            ],
            options={
                'db_table': 'tier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransferMiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_member_1', models.CharField(max_length=100)),
                ('email_member_2', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
                ('catatan', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'transfer',
                'managed': False,
            },
        ),
    ]
