# Generated by Django 5.2.13 on 2026-04-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimMiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_member', models.CharField(max_length=100)),
                ('email_staf', models.CharField(blank=True, max_length=100, null=True)),
                ('maskapai', models.CharField(max_length=10)),
                ('bandara_asal', models.CharField(max_length=3)),
                ('bandara_tujuan', models.CharField(max_length=3)),
                ('tanggal_penerbangan', models.DateField()),
                ('flight_number', models.CharField(max_length=10)),
                ('nomor_tiket', models.CharField(max_length=20)),
                ('kelas_kabin', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], max_length=20)),
                ('pnr', models.CharField(max_length=10)),
                ('status_penerimaan', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'claim_missing_miles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransferMiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_member_1', models.CharField(max_length=100)),
                ('email_member_2', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('jumlah', models.IntegerField()),
                ('catatan', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'transfer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
